/**
 * payments/routes/me.routes.js
 *
 * Self-service endpoints for the currently authenticated staff member to
 * view their own payslips and download PDF copies.
 *
 * Mount prefix in index.js: /api/me
 *
 * Endpoints (3):
 *   GET /api/me/payslips         — list own payslips (paginated by generatedAt desc)
 *   GET /api/me/payslips/:id     — single payslip JSON (includes employee + deductions)
 *   GET /api/me/payslips/:id/pdf — stream payslip as PDF (pdfkit)
 *
 * The loadPayslipForUser helper is duplicated from payroll.routes.js because
 * sibling modules must NOT import from each other's route files (Plan 11 rule:
 * direct imports from lib/ only). Both copies are tiny (8 lines). If a third
 * consumer appears, extract to lib/payroll-helpers.js.
 */

'use strict';

const PDFDocument = require('pdfkit');
const express     = require('express');
const router      = express.Router();
const prisma      = require('../../../lib/prisma');
const { requireAuth } = require('../../../lib/auth');

// ── Local helper (mirrors payroll.routes.js version) ─────────────────────────

async function loadPayslipForUser(payslipId, requestingUser) {
  const slip = await prisma.payslip.findFirst({
    where: { id: payslipId },
    include: {
      user:       true,
      payrollRun: true,
      deductions: true,
    },
  });
  if (!slip) return { error: 'not_found' };
  const isOwner = slip.userId === requestingUser?.userId;
  const isAdmin = requestingUser?.role === 'admin';
  if (!isOwner && !isAdmin) return { error: 'forbidden' };
  return { slip };
}

function streamPayslipPdf(res, slip) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `inline; filename="payslip-${slip.payrollRun.period}-${slip.user.lastName}.pdf"`,
  );
  doc.pipe(res);

  doc.fontSize(20).fillColor('#6A3FF4').text('UniFlow', { align: 'left' });
  doc.fontSize(12).fillColor('#444').text(`Payslip — ${slip.payrollRun.period}`, { align: 'right' });
  doc.moveDown(1);

  doc.fontSize(11).fillColor('#000').text(`Employee: ${slip.user.firstName} ${slip.user.lastName}`);
  doc.text(`Email:    ${slip.user.email}`);
  doc.text(`Period:   ${slip.payrollRun.period}`);
  doc.text(`Issued:   ${slip.generatedAt.toISOString().slice(0, 10)}`);
  doc.text(`Status:   ${slip.payrollRun.status}`);
  doc.moveDown(1);

  doc.fontSize(13).fillColor('#6A3FF4').text('Earnings', { underline: true });
  doc.fontSize(11).fillColor('#000');
  doc.text(`Gross Salary: ${slip.payrollRun.currency} ${parseFloat(slip.gross).toFixed(2)}`);
  doc.moveDown(0.5);

  doc.fontSize(13).fillColor('#6A3FF4').text('Deductions', { underline: true });
  doc.fontSize(11).fillColor('#000');
  if (slip.deductions.length === 0) {
    doc.text('— None —');
  } else {
    slip.deductions.forEach((d) => {
      doc.text(`• ${d.type.toUpperCase()}${d.description ? ' — ' + d.description : ''}: ${slip.payrollRun.currency} ${parseFloat(d.amount).toFixed(2)}`);
    });
  }
  doc.text(`Total Deductions: ${slip.payrollRun.currency} ${parseFloat(slip.deductionsTotal).toFixed(2)}`);
  doc.moveDown(1);

  doc.fontSize(15).fillColor('#000').text(
    `Net Pay: ${slip.payrollRun.currency} ${parseFloat(slip.net).toFixed(2)}`,
    { align: 'right' },
  );
  doc.moveDown(2);
  doc.fontSize(8).fillColor('#999').text(
    'This payslip is generated by UniFlow and is for informational purposes only.',
    { align: 'center' },
  );

  doc.end();
}

// ── Self-service: list own payslips ───────────────────────────────────────────

router.get('/payslips', requireAuth, async (req, res) => {
  try {
    const payslips = await prisma.payslip.findMany({
      where:   { userId: req.user.userId },
      orderBy: { generatedAt: 'desc' },
      include: { payrollRun: { select: { period: true, status: true, currency: true } } },
    });
    res.json({
      payslips: payslips.map((p) => ({
        id:              p.id,
        period:          p.payrollRun.period,
        status:          p.payrollRun.status,
        currency:        p.payrollRun.currency,
        gross:           parseFloat(p.gross),
        deductionsTotal: parseFloat(p.deductionsTotal),
        net:             parseFloat(p.net),
        generatedAt:     p.generatedAt,
      })),
    });
  } catch (err) {
    res.status(500).json({ error: 'Internal server error' });
  }
});

// ── Self-service: single payslip JSON ─────────────────────────────────────────

router.get('/payslips/:id', requireAuth, async (req, res) => {
  try {
    const slip = await prisma.payslip.findFirst({
      where:   { id: req.params.id },
      include: {
        user:       { select: { id: true, firstName: true, lastName: true, email: true, odId: true } },
        payrollRun: true,
        deductions: true,
      },
    });
    if (!slip) return res.status(404).json({ error: 'Payslip not found' });
    if (slip.userId !== req.user.userId && req.user.role !== 'admin') {
      return res.status(403).json({ error: 'Forbidden' });
    }
    const employeeProfile = await prisma.employeeProfile.findFirst({
      where:  { userId: slip.userId },
      select: { position: true, payrollId: true },
    });
    res.json({
      payslip: {
        id:              slip.id,
        period:          slip.payrollRun.period,
        status:          slip.payrollRun.status,
        currency:        slip.payrollRun.currency,
        notes:           slip.payrollRun.notes,
        gross:           parseFloat(slip.gross),
        deductionsTotal: parseFloat(slip.deductionsTotal),
        net:             parseFloat(slip.net),
        generatedAt:     slip.generatedAt,
        employee: {
          id:        slip.user.id,
          name:      `${slip.user.firstName} ${slip.user.lastName}`,
          email:     slip.user.email,
          odId:      slip.user.odId,
          position:  employeeProfile?.position  ?? null,
          payrollId: employeeProfile?.payrollId ?? null,
        },
        deductions: slip.deductions.map((d) => ({
          id:          d.id,
          type:        d.type,
          amount:      parseFloat(d.amount),
          description: d.description,
        })),
      },
    });
  } catch (err) {
    console.error('Self-service payslip detail error:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// ── Self-service: payslip PDF ─────────────────────────────────────────────────

router.get('/payslips/:id/pdf', requireAuth, async (req, res) => {
  const { error, slip } = await loadPayslipForUser(req.params.id, req.user);
  if (error === 'not_found') return res.status(404).json({ error: 'Payslip not found' });
  if (error === 'forbidden') return res.status(403).json({ error: 'Forbidden' });
  streamPayslipPdf(res, slip);
});

module.exports = router;

module.exports = router;
